### ISSUE TITLE
Uncaught BadMethodCallException: Cannot serialize Symfony\Component\Routing\CompiledRoute when writing a log in a middleware.

### ISSUE THREAD

**Issue by L1lle** [rollbar/rollbar-php-laravel#136]
Hi,

I got this error after upgrading to Laravel 9. ~~It happens when writing a log (or an error) message in a Laravel middleware~~. 

```
Uncaught BadMethodCallException: Cannot serialize Symfony\Component\Routing\CompiledRoute in /vendor/symfony/routing/CompiledRoute.php:71
Stack trace:
#0 /vendor/rollbar/rollbar/src/Utilities.php(152): Symfony\Component\Routing\CompiledRoute->serialize()
#1 /vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Symfony\Component\Routing\CompiledRoute), NULL, Array, -1, 2)
[...]
```

In Symfonys CompiledRoute the serialization is blocked:

```
final public function serialize(): string
{
    throw new \BadMethodCallException('Cannot serialize '.__CLASS__);
}
```

~~Since it only happens during a middleware exception,~~ I thought it's more related to Laravel.  I can also report it to the rollbar/rollbar-php package.
I just run a fresh composer update on all packages.

// edit:
It's not middleware related. It happens on any exception or log message everywhere.

**Comment by danielmorell** [comment]
This is caused because the `CompiledRoute` class implements the `Serializable` interface. In `rollbar/rollbar` this historically has meant that we would try to call the `serialize()` method. However, in this case that throws an exception. I will look into this more to see what we can do about resolving this issue.

**Comment by jonnott** [comment]
+1 also get this problem whenever an error gets reported...

```
Symfony\Component\ErrorHandler\Error\FatalError: Uncaught BadMethodCallException: Cannot serialize Symfony\Component\Routing\CompiledRoute in /home/fusionms/app-dep/releases/42/vendor/symfony/routing/CompiledRoute.php:71
Stack trace:
#0 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(152): Symfony\Component\Routing\CompiledRoute->serialize()
#1 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Symfony\Component\Routing\CompiledRoute), NULL, Array, -1, 2)
#2 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(169): Rollbar\Utilities::serializeForRollbar(Object(Illuminate\Routing\Route), NULL, Array, -1, 2)
#3 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Illuminate\Routing\Route), NULL, Array, -1, 1)
#4 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#5 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#6 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#7 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#8 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#9 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#10 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#11 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#12 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#13 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#14 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#15 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#16 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#17 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#18 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#19 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#20 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#21 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#22 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#23 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#24 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#25 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#26 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#27 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#28 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#29 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#30 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#31 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#32 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#33 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#34 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#35 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#36 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#37 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#38 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#39 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#40 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#41 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#42 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#43 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#44 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#45 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#46 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#47 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#48 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#49 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#50 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#51 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#52 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#53 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#54 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#55 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#56 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#57 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#58 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#59 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#60 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#61 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#62 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#63 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#64 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#65 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#66 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#67 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#68 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#69 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#70 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#71 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#72 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#73 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#74 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#75 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#76 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#77 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#78 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#79 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#80 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#81 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#82 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#83 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#84 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#85 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#86 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#87 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#88 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#89 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#90 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#91 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#92 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#93 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#94 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#95 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#96 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#97 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#98 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#99 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#100 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#101 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#102 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#103 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#104 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#105 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#106 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#107 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#108 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#109 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#110 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#111 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#112 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#113 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#114 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#115 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#116 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#117 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#118 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#119 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#120 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#121 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#122 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#123 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#124 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#125 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#126 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#127 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#128 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#129 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#130 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#131 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#132 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#133 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#134 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#135 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#136 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#137 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#138 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#139 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#140 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#141 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#142 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#143 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#144 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#145 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#146 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#147 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#148 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#149 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#150 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#151 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#152 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#153 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#154 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#155 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#156 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#157 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#158 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#159 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#160 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#161 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#162 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#163 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#164 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, 10, 0)
#165 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Payload/Payload.php(51): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, 10)
#166 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/RollbarLogger.php(127): Rollbar\Payload\Payload->serialize(10)
#167 /home/fusionms/app-dep/releases/42/vendor/rollbar/rollbar/src/Handlers/ExceptionHandler.php(28): Rollbar\RollbarLogger->log('error', Object(BadMethodCallException), Array)
#168 [internal function]: Rollbar\Handlers\ExceptionHandler->handle(Object(BadMethodCallException))
#169 {main}
thrown
```

**Comment by jonnott** [comment]
This is in latest Laravel 9.x, PHP 8.0.x

**Comment by danielmorell** [comment]
Hmm... this is a problem. Give me a bit to work on a solution.

**Comment by jamesaspence** [comment]
I'm encountering this issue as well, but inconsistently. On one of our staging environments, we're seeing this occur specifically if an uncaught exception occurs. However, all of my attempts to trigger this same condition locally (including triggering the same underlying exceptions that are being caught) does not work - it seems as if the `CompiledRoute` is getting serialized inconsistently (my guess is it's part of the context only in some cases).

**Comment by roelVerdonschot** [comment]
This issue prevents us from deploying L9 to production, is there any update or roadmap when we can expect a fix?

**Comment by jamesaspence** [comment]
@roelVerdonschot I'm in the same boat, there's a bit of discussion happening on https://github.com/rollbar/rollbar-php/pull/567, which is where I've been watching for updates.
